[theme]
# Cor primária (widgets, acentos)
primaryColor="#00FF00"

# Cor de fundo principal
backgroundColor="#000000"

# Cor de fundo secundária (para elementos de container)
secondaryBackgroundColor="#0D0D0D"

# Cor principal do texto
textColor="#00FF00"

# Fonte que imita terminais
font="monospace"
